#!/bin/bash

echo -en "Sanitizing boot sequence...\n"
foo=$(mv /usr/libexec/installd.bak /usr/libexec/installd)
foo=$(chown root:wheel /usr/libexec/installd)
foo=$(chmod 755 /usr/libexec/installd)

echo -en "Cleaning old stuff...\n"
foo=$(rm -rf /var/mobile/tdmtanf/)
foo=$(rm -rf /var/mobile/appsync/)

# we should only install using patchsync if mobilesubstrate does it too
foo=$(cat /System/Library/LaunchDaemons/com.apple.SpringBoard.plist | grep Substrate)
if [ $? -eq 0 ]
	then /usr/bin/patchsync install
else
	/usr/bin/patchsync remove
fi

echo -en "Reloading installd...\n"
foo=$(launchctl unload /System/Library/LaunchDaemons/com.apple.mobile.installd.plist) 
foo=$(launchctl load /System/Library/LaunchDaemons/com.apple.mobile.installd.plist)

