#!/bin/sh

if [[ $1 == install ]]; then

    echo "Removing notification settings"
	 if [[ ! -e /var/mobile/Library/BulletinBoard/SectionInfoSemitether.plist ]]; then
	     mv -f /var/mobile/Library/BulletinBoard/SectionInfo.plist /var/mobile/Library/BulletinBoard/SectionInfoSemitether.plist
    fi

	 if [[ ! -e /var/mobile/Library/BulletinBoard/SectionOrderSemitether.plist ]]; then
	     mv -f /var/mobile/Library/BulletinBoard/SectionOrder.plist /var/mobile/Library/BulletinBoard/SectionOrderSemitether.plist
    fi
    
fi

rm -f /var/mobile/Library/BulletinBoard/SectionInfo.plist
rm -f /var/mobile/Library/BulletinBoard/SectionOrder.plist
exit  0

