#!/bin/bash
# postrm
function finish() {
	f="${1}"
	[[ -z "${f}" || -z "${CYDIA}" ]] && return
	cydia=(${CYDIA})
	[[ ${cydia[1]} -eq 1 ]] || return
	echo "finish:${f}" >&${cydia[0]}
}
finish restart
exit 0
