#!/bin/sh
echo "..................................."
echo "Get ready for installing"
echo "..................................."
echo "Spire for iOS5.1.1"
echo "..................................."
echo "Backing up files..."
mv /System/Library/CoreServices/SpringBoard.app/K48AP.plist /System/Library/CoreServices/SpringBoard.app/K48AP.plist_nosiri
mv /System/Library/CoreServices/SpringBoard.app/N81AP.plist /System/Library/CoreServices/SpringBoard.app/N81AP.plist_nosiri
mv /System/Library/CoreServices/SpringBoard.app/N18AP.plist /System/Library/CoreServices/SpringBoard.app/N18AP.plist_nosiri
mv /System/Library/CoreServices/SpringBoard.app/N88AP.plist /System/Library/CoreServices/SpringBoard.app/N88AP.plist_nosiri
mv /System/Library/CoreServices/SpringBoard.app/N90AP.plist /System/Library/CoreServices/SpringBoard.app/N90AP.plist_nosiri
mv /System/Library/CoreServices/SpringBoard.app/N92AP.plist /System/Library/CoreServices/SpringBoard.app/N92AP.plist_nosiri
mv /System/Library/CoreServices/SpringBoard.app/N94AP.plist /System/Library/CoreServices/SpringBoard.app/N94AP.plist_nosiri
mv /System/Library/LaunchDaemons/com.apple.SpringBoard.plist /System/Library/LaunchDaemons/com.apple.SpringBoard.plist_nosiri
echo "..................."
echo "Just ignore mistakes. We are ready for installing."
echo "..................."
echo "Installing Spire for iOS 5.1.1"
echo "..................."
