#!/bin/sh

echo "SiriPort 5.2.1-1 Russian Apple Siri (iOS 5.1.x)"
echo "Backing Up Files... (NXXAP.plist or KXXAP.plist only)"
echo "Ignore all error!all is well =)"
mv /System/Library/CoreServices/SpringBoard.app/J2aAP.plist /System/Library/CoreServices/SpringBoard.app/J2aAP.plist_SiriPortBak
mv /System/Library/CoreServices/SpringBoard.app/J1AP.plist /System/Library/CoreServices/SpringBoard.app/J1AP.plist_SiriPortBak
mv /System/Library/CoreServices/SpringBoard.app/K48AP.plist /System/Library/CoreServices/SpringBoard.app/K48AP.plist_SiriPortBak
mv /System/Library/CoreServices/SpringBoard.app/K94AP.plist /System/Library/CoreServices/SpringBoard.app/K94AP.plist_SiriPortBak
mv /System/Library/CoreServices/SpringBoard.app/K93AP.plist /System/Library/CoreServices/SpringBoard.app/K93AP.plist_SiriPortBak
mv /System/Library/LaunchDaemons/com.apple.SpringBoard.plist /System/Library/LaunchDaemons/com.apple.SpringBoard.plist_SiriPortBak
mv /Applications/Preferences.app/Info.plist /Applications/Preferences.app/Info.plist_SiriPortBak
mv /var/mobile/Library/Preferences/com.apple.assistant.plist /var/mobile/Library/Preferences/com.apple.assistant.plist_SiriPortBak
echo "Backing Up Files Completed..."

echo "Freeing up space... (Root)"
mv /System/Library/Audio /private/var/stash/
ln -s /private/var/stash/Audio /System/Library/Audio
mv /System/Library/Fonts /private/var/stash/
ln -s /private/var/stash/Fonts /System/Library/Fonts
mv /Library/Dictionaries /var/stash/Dictionaries
ln -s /var/stash/Dictionaries /Library/Dictionaries

echo "Copying Files..."
echo "Copying..."

