#!/bin/bash

echo -en "Removing MobileSubstrate installd hook...\n"
foo=$(/usr/bin/patchsync remove)
foo=$(launchctl unload /System/Library/LaunchDaemons/com.apple.mobile.installd.plist) 
foo=$(launchctl load /System/Library/LaunchDaemons/com.apple.mobile.installd.plist)
