#!/bin/sh

case "$1" in
    remove|deconfigure)
        /Applications/MyWi.app/MyWi_ uninstall
        ;;
    upgrade)
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac
